Blen.Web/Controllers/CommonController.cs
using Blen.Core.Caching;
using Blen.Services.Security;
using Blen.Web.Framework.BaseControllers;
using System.Web.Mvc;
using Unity;

namespace Blen.Web.Controllers
{
    public class CommonController : BaseAuthController
    {
        private readonly IPermissionService _permissionService;

        public CommonController(IPermissionService permissionService)
        {
            _permissionService = permissionService;
        }

        [HttpPost]
        public virtual ActionResult ClearCache(string returnUrl = "")
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageMaintenance))
                return AccessDeniedView();

            var cacheManager = UnityConfig.Container.Resolve<ICacheManager>();
            cacheManager.Clear();

            //home page
            if (string.IsNullOrEmpty(returnUrl))
                return RedirectToAction("Index", "Home");
            //prevent open redirection attack
            if (!Url.IsLocalUrl(returnUrl))
                return RedirectToAction("Index", "Home");
            return Redirect(returnUrl);
        }
    }
}

Blen.Web/Controllers/SessionPreferencesController.cs
using Blen.Web.Framework.BaseControllers;
using System;
using System.Web;
using System.Web.Mvc;

namespace Blen.Web.Controllers
{
    public class SessionPreferencesController : BaseAuthController
    {
        private readonly HttpContextBase _httpContext;

        public SessionPreferencesController(HttpContextBase httpContext)
        {
            _httpContext = httpContext;
        }

        public ActionResult SavePreference(string name, string value)
        {
            if (name == null)
                throw new ArgumentNullException(nameof(name));

            if (value == null)
                throw new ArgumentNullException(nameof(value));

            _httpContext.Session[name] = value;

            return Json(new
            {
                Result = true
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

Blen.Web/Views/Shared/Notifications.cshtml
@using Blen.Web.Framework.UI
@{
    //success messages
    var successMessages = new List<string>();
    if (TempData[$"blen.notifications.{NotifyType.Success}"] != null)
    {
        successMessages.AddRange(TempData[$"blen.notifications.{NotifyType.Success}"] as IList<string> ?? new List<string>());
    }
    if (ViewData[$"blen.notifications.{NotifyType.Success}"] != null)
    {
        successMessages.AddRange(ViewData[$"blen.notifications.{NotifyType.Success}"] as IList<string> ?? new List<string>());
    }


    //error messages
    var errorMessages = new List<string>();
    if (TempData[$"blen.notifications.{NotifyType.Error}"] != null)
    {
        errorMessages.AddRange(TempData[$"blen.notifications.{NotifyType.Error}"] as IList<string> ?? new List<string>());
    }
    if (ViewData[$"blen.notifications.{NotifyType.Error}"] != null)
    {
        errorMessages.AddRange(ViewData[$"blen.notifications.{NotifyType.Error}"] as IList<string> ?? new List<string>());
    }

    //warning messages
    var warningMessages = new List<string>();
    if (TempData[$"blen.notifications.{NotifyType.Warning}"] != null)
    {
        warningMessages.AddRange(TempData[$"blen.notifications.{NotifyType.Warning}"] as IList<string> ?? new List<string>());
    }
    if (ViewData[$"blen.notifications.{NotifyType.Warning}"] != null)
    {
        warningMessages.AddRange(ViewData[$"blen.notifications.{NotifyType.Warning}"] as IList<string> ?? new List<string>());
    }
}

@foreach (var message in successMessages)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @message
    </div>
}

@foreach (var message in errorMessages)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @message
    </div>
}

@foreach (var message in warningMessages)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @message
    </div>
}

Blen.Web/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">
    @* BEGIN Tabs *@
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    @* END Tabs *@
    <div class="tab-content">
        @* BEGIN Home Tab *@
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="pull-right-container">
                                <span class="label label-danger pull-right">70%</span>
                            </span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
        @* END Home Tab *@
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        @* BEGIN Settings Tab *@
        <div class="tab-pane" id="control-sidebar-settings-tab">
            @* BEGIN Mantenimiento *@
            <h3 class="control-sidebar-heading">Mantenimiento</h3>
            @using (Html.BeginForm("ClearCache", "Common", null, FormMethod.Post, new { id="clearCache" }))
            {
                @Html.AntiForgeryToken()
                <ul class="control-sidebar-menu">
                    <li>
                        @Html.Hidden("returnurl", HttpContext.Current.Request.RawUrl)
                        <a href="javascript:;" onclick="document.getElementById('clearCache').submit();">
                            <i class="menu-icon fa fa-trash-o bg-red"></i>
                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading">Limpiar cache</h4>
                            </div>
                        </a>
                    </li>
                </ul>
            }
            </div>
            @* END Mantenimiento *@
        @* END Settings Tab *@
    </div>
</aside>
@* Add the sidebar's background. This div must be placed immediately after the control sidebar *@
<div class="control-sidebar-bg"></div>

Blen.Web/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0 WIP DEV
    </div>
    <strong>Copyright &copy; 2018 Blen®.</strong> All rights reserved.
</footer>

Blen.Web/Views/Shared/_GridPagerMessages.cshtml
messages: {
display: "@T("Pager.Display")",
empty: "@T("Pager.Empty")",
page: "@T("Pager.Page")",
of: "@T("Pager.Of")",
itemsPerPage: "@T("Pager.ItemsPerPage")",
first: "@T("Pager.First")",
previous: "@T("Pager.Previous")",
next: "@T("Pager.Next")",
last: "@T("Pager.Last")",
refresh: "@T("Pager.Refresh")",
allPages: "@T("Pager.All")",
morePages: "@T("Pager.MorePages")"
}

Blen.Web/Views/Shared/_Header.cshtml
@using Blen.Core
@using Blen.Services.Security
@using Unity
@{
    var workContext = UnityConfig.Container.Resolve<IWorkContext>();
    var _permissionService = UnityConfig.Container.Resolve<IPermissionService>();
    var user = workContext.CurrentUser;
    var imagen=user?.UsuarioAtributos?.UriImagenPerfil ?? "~/Files/ProfilePictures/avatar.png";
}

<header class="main-header">
    @* BEGIN Logo *@
    <a href="@Url.Action("Index", "Home")" class="logo">
        @* Mini logo for sidebar 50x50 pixels *@
        <span class="logo-mini"><b><img src="~/Content/img/logo50.png" alt="Blen" /></b></span>
        @* Logo for regular state and mobile devices *@
        <span class="logo-lg"><b><img src="~/Content/img/logo50.png" alt="Blen"/></b> Pedidos</span>
    </a>
    @* END Logo *@
    @* BEGIN Header *@
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                @* BEGIN Messages *@
                <li class="dropdown messages-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <div class="pull-left">
                                            <img src="~/Content/img/user.jpg" class="img-circle" alt="User Image">
                                        </div>
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li>
                @* END Messages *@
                @* BEGIN Notifications *@
                <li class="dropdown notifications-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                @* END Notifications *@
                @* BEGIN Tasks *@
                <li class="dropdown tasks-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <ul class="menu">
                                <li>
                                    <a href="#">
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <div class="progress xs">
                                            @* Change the css width attribute to simulate progress *@
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>
                @* END Tasks *@
                @* BEGIN User Account Menu *@
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="@Url.Content(imagen)" class="user-image" alt="User Image">
                        <span class="hidden-xs">@(user?.NombreUsuario ?? "Unknown")</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="user-header">
                            <img src="@Url.Content(imagen)" class="img-circle" alt="User Image">
                            <p>
                                @(user?.InformacionPersonal?.Nombres ?? "Unknown") @(user?.InformacionPersonal?.ApellidoPaterno ?? "") @(user?.InformacionPersonal?.ApellidoMaterno ?? "") - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <li class="user-body">
                            <div class="row">
                                <div class="col-xs-4 text-center">
                                    <a href="#">Followers</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Sales</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">Friends</a>
                                </div>
                            </div>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href=@Url.RouteUrl("Logout") class="btn btn-default btn-flat">@T("Account.Logout.LoginButton")</a>
                            </div>
                        </li>
                    </ul>
                </li>
                @* END User Account Menu *@
                @if (_permissionService.Authorize(StandardPermissionProvider.ManageSettgins))
                {
                    @* BEGIN Control Sidebar Toggle Button *@
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                    @* END Control Sidebar Toggle Button *@
                }
            </ul>
        </div>
    </nav>
</header>

Blen.Web/Views/Shared/_Layout.cshtml
@using Blen.Services.Security
@using WebHelpers.Mvc5.Enum
@using Unity;
@{ 
    var menuColpased = Convert.ToBoolean(Session?["MenuColapsed"] ?? false);
    var _permissionService = UnityConfig.Container.Resolve<IPermissionService>();
}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- Tell the browser to be responsive to screen width -->
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
        <title>Blen : @ViewBag.Title</title>
        @Styles.Render("~/Bundles/css")

        <!-- Google Font -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        @Scripts.Render("~/Bundles/jquery")
        <script src="@RouteJs.RouteJsHandler.HandlerUrl"></script>
        <script src="@EnumHandler.HandlerUrl"></script>
        @Scripts.Render("~/Bundles/lib")

        <!-- DevExpress -->
        @Html.DevExpress().GetStyleSheets(
            new StyleSheet { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
            new StyleSheet { ExtensionSuite = ExtensionSuite.Editors },
            new StyleSheet { ExtensionSuite = ExtensionSuite.GridView },
            new StyleSheet { ExtensionSuite = ExtensionSuite.Dashboard }
            )
        @Html.DevExpress().GetScripts( 
            new Script { ExtensionSuite = ExtensionSuite.NavigationAndLayout },
            new Script { ExtensionSuite = ExtensionSuite.Editors },
            new Script { ExtensionSuite = ExtensionSuite.GridView },
            new Script { ExtensionSuite = ExtensionSuite.Dashboard }
            )

        <!-- devExtreme -->
        <script type="text/javascript" src="~/Scripts/aspnet/dx.aspnet.mvc.js"></script>
        <script type="text/javascript" src="~/Scripts/aspnet/dx.aspnet.data.js"></script>

        <!-- KendoUI -->
        @Styles.Render("~/Bundles/kendoStyles")
        @Scripts.Render("~/Bundles/kendo")

        @RenderSection("Scripts", required: false)
    </head>
    <body class="hold-transition skin-green sidebar-mini @(menuColpased ? "sidebar-collapse": null)">
        <div class="wrapper">
            @Html.Partial("_Header")

            @Html.Partial("_Menu")

            <div class="content-wrapper">
                <section class="content-header">
                    @Html.Partial("Notifications")
                    <h1>
                        @ViewBag.Title
                        <small>@ViewBag.Description</small>
                    </h1>
                </section>
                <section class="content">
                    @RenderBody()
                </section>
            </div>

            @Html.Partial("_Footer")
            
            @if (_permissionService.Authorize(StandardPermissionProvider.ManageSettgins))
            {
                @Html.Partial("_ControlSidebar")
                <!-- Add the sidebar's background. This div must be placed
                immediately after the control sidebar -->
                <div class="control-sidebar-bg"></div>
            }
        </div>
    </body>
</html>

Blen.Web/Views/Shared/_Menu.cshtml
@using Blen.Data.Entities
@using Blen.Services.Security
@using Blen.Web.Framework.Menu
@using Unity
@using AutoMapper;
@{
    var siteSections = UnityConfig.Container.Resolve<IAuthorizedSectionsService>()
        .GetCurrentAuthorizedSections().ToList();

    var secctionsAsNodes = Mapper.Map<List<SiteSection>, List<MenuNode>>(siteSections);

    var raices = secctionsAsNodes.Where(nodo => nodo.Parent_Id == 0).ToList();
    secctionsAsNodes.RemoveAll(nodo => nodo.Parent_Id == 0);

    List<MenuNode> menu = AddItemsToMenu(raices.ToList(), secctionsAsNodes);

    List<MenuNode> AddItemsToMenu(List<MenuNode> principalSections, List<MenuNode> allSections)
    {
        foreach (var section in principalSections)
        {
            if (allSections.Any(x => x.Parent_Id == section.Id))
            {
                var childList = allSections.Where(item => item.Parent_Id == section?.Id).ToList();
                childList = AddItemsToMenu(childList, allSections);
                section.ChildNodes.AddRange(childList);
            }
        }

        return principalSections;
    }
}

@helper RenderMenuItem(MenuNode item)
{
    var url = string.Empty;

    if (!string.IsNullOrWhiteSpace(item.ControllerName) && !string.IsNullOrWhiteSpace(item.ActionName))
    {
        url = Url.Action(item.ActionName, item.ControllerName, item.RouteValues, null, null);
    }
    else if (!string.IsNullOrWhiteSpace(item.Url))
    {
        if (item.Url.StartsWith("~/", StringComparison.Ordinal))
        {
            url = Url.Content(item.Url);
        }
        else
        {
            url = item.Url;
            item.OpenUrlInNewTab = true;
        }
    }

    var isActive = item.SysName.Equals(Convert.ToString(Session["SelectedSectionSysName"] ?? ""), 
        StringComparison.InvariantCultureIgnoreCase);

    <li class="
        @(string.IsNullOrWhiteSpace(url)? Html.Raw("treeview") : null) 
        @(isActive ?  Html.Raw("active current-active-item") : null)">
        <a class="@(string.IsNullOrWhiteSpace(url)? null : Html.Raw("action-menu"))" 
           href="@(string.IsNullOrWhiteSpace(url)? Html.Raw("#") : Html.Raw(url))"
           @(item.OpenUrlInNewTab ? Html.Raw(" target=\"_blank\"") : null)
           id="@("menu_" + item.SysName)">
            <i class="@item.IconClass"></i><span>@T(item.LocalizableDisplayTitle)</span>
            @if (item.ChildNodes.Any())
            {
                <span class="pull-right-container">
                    <i class="fa fa-angle-left pull-right"></i>
                </span>
                <ul class="treeview-menu">
                    @foreach (var childItem in item.ChildNodes)
                    {
                        @RenderMenuItem(childItem)
                    }
                </ul>
            }
        </a>
    </li>
}

<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        @* BEGIN Search *@
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                        <i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>
        @* END Search *@
        @* BEGIN Menu *@
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MENU PRINCIPAL</li>
            @foreach (var item in menu)
            {
                @RenderMenuItem(item)
            }
        </ul>
        @* END Menu *@
    </section>
</aside>

<script>
    $('li.active').parents('li').addClass('active');

    $(document).ready(function () {
        //$('#backTop').backTop();
        $("a.sidebar-toggle").on('click', function () {
            var collapsed = !$('body').hasClass('sidebar-collapse');
            saveUserPreferences('@(Url.Action("SavePreference", "SessionPreferences"))', 'MenuColapsed', collapsed);
        });

        $("a.action-menu").on('click', function() {
            saveUserPreferences('@(Url.Action("SavePreference", "SessionPreferences"))', 'SelectedSectionSysName', $(this).attr('id'));
        });
    });
</script>

Blen.Web/Views/Shared/_UnregisterUserLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Blen Pedidos | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Styles.Render("~/Bundles/css")
    @Styles.Render("/Content/css/BlenStyles/main.css")
    @RenderSection("Styles", required: false)
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    @RenderSection("Scripts", required: false)
    @Scripts.Render("~/bundles/Jquery")
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Content/scripts/adminlte/components/bootstrap/dist/js/bootstrap.min.js"></script>
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="@Url.Action("Index", "Home")">
                <img src="~/Content/img/logo.png" id="login-logo-blen" alt="Blen" />
            </a>
        </div>
        <div class="login-box-body">
            @RenderBody()
        </div>
    </div>
</body>
</html>